### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-extensions#19]

**Comment by ericearl** [comment]
@Remi-Gau Can we re-use this license and just update the copyright date?

https://github.com/bids-standard/bids-specification/blob/master/LICENSE

**Comment by Remi-Gau** [comment]
yes: let's keep the same license

**Comment by ericearl** [comment]
PR added as promised

**Comment by Remi-Gau** [comment]
closed by #20
