### ISSUE TITLE
Incorporate general conventions for spatial derivatives

### ISSUE THREAD

**Issue by arokem** [bids-standard/bids-extensions#24]
As follow up on https://github.com/bids-standard/bids-specification/issues/1602, these ideas should now be incorporated into the BEP guidelines in this repo. I don't see any page dedicated specifically to extensions related to derivatives, so maybe it would be good to start such a page?

**Comment by PeerHerholz** [comment]
Something like "General conventions"?

**Comment by arokem** [comment]
How about something slightly more specific like "General conventions for spatial derivatives?"

**Comment by PeerHerholz** [comment]
Sure thing, I don't have any specific preference/opinion re this but just thought that if other "general conventions" emerge, they could be added as sections/sub-pages.

**Comment by effigies** [comment]
Yeah, I think it makes sense to have a page that's "General conventions" with a little blurb about what the overall purpose is, and then a specific section on spatial derivatives. I don't think this decision deserves a top-level heading, and it will presumably not be a unique decision.

**Comment by PeerHerholz** [comment]
First draft is now up for discussion/feedback [here](https://github.com/bids-standard/bids-extensions/pull/26).
