### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by effigies** [bids-standard/bids-extensions#5]
# Guide

* Missing intro explaining what, just dives into "why?"
* s/concision/conciseness/
* Extraneous comma in "The most common situation where the trade-off between flexibility and ease of tool building comes up, is choosing file formats."

# Submission process

* "These examples will be used to test the validator is working properly" should not be a separate bullet point from the above.

# Extending the Schema and Validator

* s/incubent/incumbent/
* s/by product/byproduct/

**Comment by ericearl** [comment]
@bendhouseart Does #6 address all of @effigies points here? Can we close this?
